"""Template strings for Mirror project and application scaffolding."""

from __future__ import annotations


def _text(*lines: str) -> str:
    return "\n".join(lines) + "\n"


_PROJECT_FILES: dict[str, str] = {
    "README.md": _text(
        "# {{PROJECT_NAME}}",
        "",
        "Created with `mirror startproject`.",
        "",
        "## Next steps",
        "",
        "1. Edit `config/settings.py` to select the active components.",
        "2. Add app-specific code under `apps/` with `mirror startapp`.",
        "3. Run `mirror doctor` from this directory to verify the scaffold.",
    ),
    "pyproject.toml": _text(
        "[build-system]",
        'requires = ["setuptools>=61.0", "wheel"]',
        'build-backend = "setuptools.build_meta"',
        "",
        "[project]",
        'name = "{{PROJECT_NAME}}"',
        'version = "0.1.0"',
        'description = "Mirror project scaffold"',
        'requires-python = ">=3.10"',
        "dependencies = [",
        '    "mirror-core>=0.1.0",',
        '    "mirror-cli>=0.1.0",',
        "]",
        "",
        "[tool.setuptools.packages.find]",
        'where = ["."]',
        'include = ["config*", "apps*"]',
        "namespaces = false",
        "",
        "[tool.pytest.ini_options]",
        'testpaths = ["tests"]',
        'python_files = ["test_*.py"]',
    ),
    "manage.py": _text(
        "#!/usr/bin/env python3",
        '"""Mirror project command entry point."""',
        "",
        "from mirror_cli.main import app",
        "",
        "",
        'if __name__ == "__main__":',
        "    app()",
    ),
    "config/__init__.py": _text('"""Project configuration package for Mirror."""'),
    "config/settings.py": _text(
        '"""Project-level Mirror settings."""',
        "",
        "from mirror_core.settings import MirrorSettings",
        "",
        "settings = MirrorSettings(",
        '    application_name="{{PROJECT_NAME}}",',
        '    worker_backend="inline",',
        ")",
    ),
    "config/asgi.py": _text(
        '"""ASGI placeholder for the Mirror project."""',
        "",
        "from config.settings import settings as _settings",
        "",
        "application = None",
    ),
    "config/wsgi.py": _text(
        '"""WSGI placeholder for the Mirror project."""',
        "",
        "from config.settings import settings as _settings",
        "",
        "application = None",
    ),
    "config/urls.py": _text(
        '"""URL placeholder for the Mirror project."""',
        "",
        "urlpatterns: list[str] = []",
    ),
    "apps/__init__.py": _text('"""Application packages for the Mirror project."""'),
    "apps/core/__init__.py": _text(
        '"""Default application package created by `mirror startproject`."""'
    ),
    "apps/core/config.py": _text(
        '"""Application configuration for the default Mirror app."""',
        "",
        "from dataclasses import dataclass",
        "",
        "",
        "@dataclass(frozen=True)",
        "class AppConfig:",
        '    """Configuration for a Mirror application bundle."""',
        "",
        '    name: str = "core"',
        '    label: str = "core"',
        '    pipelines_module: str = "apps.core.pipelines"',
        '    middleware_module: str = "apps.core.middleware"',
        '    signals_module: str = "apps.core.signals"',
    ),
    "apps/core/pipelines.py": _text(
        '"""Pipeline definitions for the default Mirror app."""',
        "",
        "from mirror_core.pipeline import Pipeline",
        "",
        'core_pipeline = Pipeline(id="core", steps=[])',
    ),
    "apps/core/tasks.py": _text(
        '"""Task registration helpers for the default Mirror app."""',
        "",
        "from collections.abc import Sequence",
        "",
        "",
        "def list_tasks() -> Sequence[str]:",
        '    """Return registered task names for the scaffold app."""',
        "",
        "    return ()",
    ),
    "apps/core/middleware.py": _text(
        '"""Middleware registration helpers for the default Mirror app."""',
        "",
        "from collections.abc import Sequence",
        "",
        "",
        "def list_middleware() -> Sequence[str]:",
        '    """Return middleware names for the scaffold app."""',
        "",
        "    return ()",
    ),
    "apps/core/signals.py": _text(
        '"""Signal registration helpers for the default Mirror app."""',
        "",
        "from collections.abc import Sequence",
        "",
        "",
        "def list_signals() -> Sequence[str]:",
        '    """Return signal names for the scaffold app."""',
        "",
        "    return ()",
    ),
    "apps/core/workers.py": _text(
        '"""Worker registration helpers for the default Mirror app."""',
        "",
        "from collections.abc import Sequence",
        "",
        "",
        "def list_workers() -> Sequence[str]:",
        '    """Return worker names for the scaffold app."""',
        "",
        "    return ()",
    ),
    "tests/test_project_smoke.py": _text(
        '"""Smoke tests for the generated Mirror project scaffold."""',
        "",
        "from config.settings import settings",
        "",
        "",
        "def test_project_settings_load() -> None:",
        '    """Project settings should import and expose the application name."""',
        "",
        "    assert settings.application_name",
        '    assert settings.worker_backend == "inline"',
    ),
    "docs/README.md": _text(
        "# Project documentation",
        "",
        "Use this directory for project-specific decisions, ADRs, and runbooks.",
        "Mirror's repository-level docs describe the framework; this folder is",
        "where the generated project records its own implementation details.",
    ),
}

_APP_FILES: dict[str, str] = {
    "__init__.py": _text('"""Mirror application package scaffold."""'),
    "config.py": _text(
        '"""Application configuration for {{APP_NAME}}."""',
        "",
        "from dataclasses import dataclass",
        "",
        "",
        "@dataclass(frozen=True)",
        "class AppConfig:",
        '    """Metadata for a generated Mirror application."""',
        "",
        '    name: str = "{{APP_NAME}}"',
        '    label: str = "{{APP_NAME}}"',
        '    pipelines_module: str = "apps.{{APP_NAME}}.pipelines"',
        '    middleware_module: str = "apps.{{APP_NAME}}.middleware"',
        '    signals_module: str = "apps.{{APP_NAME}}.signals"',
    ),
    "pipelines.py": _text(
        '"""Pipeline definitions for {{APP_NAME}}."""',
        "",
        "from mirror_core.pipeline import Pipeline",
        "",
        'app_pipeline = Pipeline(id="{{APP_NAME}}", steps=[])',
    ),
    "tasks.py": _text(
        '"""Task helpers for {{APP_NAME}}."""',
        "",
        "from collections.abc import Sequence",
        "",
        "",
        "def list_tasks() -> Sequence[str]:",
        '    """Return task names registered by the application scaffold."""',
        "",
        "    return ()",
    ),
    "middleware.py": _text(
        '"""Middleware helpers for {{APP_NAME}}."""',
        "",
        "from collections.abc import Sequence",
        "",
        "",
        "def list_middleware() -> Sequence[str]:",
        '    """Return middleware names registered by the application scaffold."""',
        "",
        "    return ()",
    ),
    "signals.py": _text(
        '"""Signals for {{APP_NAME}}."""',
        "",
        "from collections.abc import Sequence",
        "",
        "",
        "def list_signals() -> Sequence[str]:",
        '    """Return signal names registered by the application scaffold."""',
        "",
        "    return ()",
    ),
    "workers.py": _text(
        '"""Worker helpers for {{APP_NAME}}."""',
        "",
        "from collections.abc import Sequence",
        "",
        "",
        "def list_workers() -> Sequence[str]:",
        '    """Return worker names registered by the application scaffold."""',
        "",
        "    return ()",
    ),
    "README.md": _text(
        "# {{APP_NAME}}",
        "",
        "Generated with `mirror startapp`.",
        "",
        "Place pipelines, middleware, tasks, workers, and signals here.",
    ),
    "tests.py": _text(
        '"""Smoke tests for {{APP_NAME}}."""',
        "",
        "",
        "def test_app_importable() -> None:",
        '    """The scaffolded application module should import cleanly."""',
        "",
        "    assert True",
    ),
}
