"""Structural protocol for the Executor's runtime interface.

The executor is split into mixins (scheduling, invocation, context, metadata,
policy, resume). Each mixin needs to call methods and read attributes owned by
sibling mixins and by ``Executor`` itself. mypy rejects ``self: Executor``
annotations inside the mixins because a mixin class is not a subtype of the
concrete ``Executor``; annotating ``self`` as this Protocol instead lets every
mixin see the full runtime surface. ``Executor`` implements it structurally.
"""

from __future__ import annotations

import asyncio
from collections.abc import Mapping
from typing import Any, Protocol
from uuid import UUID

from pydantic import BaseModel

from mirror_core.conditions import ConditionEvaluator
from mirror_core.execution import CapabilityContext, ExecutionContext
from mirror_core.executor.models import ExecutionResult, ExecutionRun
from mirror_core.executor.types import CompensationHandler, Runner
from mirror_core.executor_support import (
    CheckpointCoordinator,
    CompensationInvoker,
    DeadLetterRecorder,
    PolicyInvoker,
    RunnerContext,
)
from mirror_core.metadata import MetadataRecord, MetadataStore
from mirror_core.middleware import MiddlewareChain, MiddlewareContext, MiddlewareInvocation
from mirror_core.planner import CompiledStep, ExecutionPlan
from mirror_core.resource import ProducerRef, ResourceEnvelope
from mirror_core.storage import BlobStore
from mirror_core.workers import CheckpointStore, DeadLetterQueue


class ExecutorProto(Protocol):
    components: Mapping[tuple[str, str] | str, Any]
    max_concurrency: int
    signal_bus: Any | None
    middleware_chain: MiddlewareChain | None
    middleware_chains: Mapping[str, MiddlewareChain]
    metadata_store: MetadataStore | None
    blob_store: BlobStore | None
    checkpoint_store: CheckpointStore | None
    dead_letter_queue: DeadLetterQueue | None
    compensation_handler: CompensationHandler | None
    _condition_evaluator: ConditionEvaluator
    _checkpoint_coordinator: CheckpointCoordinator
    _dead_letter_recorder: DeadLetterRecorder
    _compensation_invoker: CompensationInvoker
    _policy_invoker: PolicyInvoker
    _active_runs: dict[UUID, ExecutionRun]

    async def execute(
        self,
        plan: ExecutionPlan,
        inputs: Mapping[str, Any] | None = None,
        runner: Runner | None = None,
        resume_from: tuple[UUID, str] | None = None,
    ) -> dict[str, ResourceEnvelope]: ...
    async def execute_run(
        self,
        plan: ExecutionPlan,
        inputs: Mapping[str, Any],
        runner: Runner | None = None,
        resume_from: tuple[UUID, str] | None = None,
    ) -> ExecutionResult: ...
    async def _emit(self, signal: str, **kwargs: Any) -> None: ...

    async def _drive_run(self, run: ExecutionRun, plan: ExecutionPlan, runner: Runner | None) -> ExecutionResult: ...
    @staticmethod
    def _pending_steps(run: ExecutionRun) -> set[str]: ...
    def _ready_steps(self, run: ExecutionRun, pending: set[str]) -> list[str]: ...
    async def _schedule_ready_steps(self, run: ExecutionRun, ready: list[str], semaphore: asyncio.Semaphore, runner: Runner | None, pending: set[str]) -> None: ...
    async def _drain_completed_tasks(self, run: ExecutionRun) -> None: ...
    async def _await_remaining_tasks(self, run: ExecutionRun) -> None: ...
    def _finalize_aborted_run(self, run: ExecutionRun) -> None: ...
    @staticmethod
    def _can_run(run: ExecutionRun, step_id: str) -> bool: ...
    @staticmethod
    def _cancel_pending(run: ExecutionRun) -> None: ...
    @staticmethod
    def _skip_unrunnable_steps(run: ExecutionRun) -> None: ...
    @staticmethod
    def _cancel_tasks(run: ExecutionRun, except_step: str | None = None) -> None: ...
    def cancel(self, run_id: UUID | None = None) -> None: ...
    async def _run_step(self, run: ExecutionRun, step_id: str, semaphore: asyncio.Semaphore, runner_override: Runner | None) -> None: ...
    async def _prepare_step(self, run: ExecutionRun, compiled: CompiledStep, step: Any, inputs: Mapping[str, Any]) -> bool: ...
    async def _invoke_step(self, run: ExecutionRun, compiled: CompiledStep, step: Any, inputs: Mapping[str, Any], runner_override: Runner | None) -> None: ...
    @staticmethod
    def _build_request(compiled: CompiledStep, inputs: Mapping[str, Any]) -> BaseModel: ...
    def _build_result_envelope(self, run: ExecutionRun, compiled: CompiledStep, step: Any, payload: BaseModel, provider_config: Any) -> ResourceEnvelope: ...
    async def _invoke_with_fallbacks(self, compiled: CompiledStep, request: BaseModel, runner: Runner, run: ExecutionRun) -> tuple[BaseModel, Any]: ...
    async def _invoke_with_policies(self, compiled: CompiledStep, provider: Any, provider_config: Any, request: BaseModel, runner: Runner, run: ExecutionRun) -> BaseModel: ...
    async def _invoke(self, compiled: CompiledStep, provider: Any, provider_config: Any, request: BaseModel, runner: Runner, run: ExecutionRun) -> BaseModel: ...
    async def _run_middleware_chain(self, chain: MiddlewareChain | None, invocation: MiddlewareInvocation, runner: Runner, runner_context: RunnerContext) -> BaseModel: ...
    def _get_runner(self, compiled: CompiledStep) -> Runner: ...
    def _get_provider(self, compiled: CompiledStep, provider_config: Any) -> Any: ...
    @staticmethod
    def _condition_context(run: ExecutionRun, compiled: CompiledStep, inputs: Mapping[str, Any]) -> dict[str, Any]: ...
    @staticmethod
    def _evaluate_condition(condition: str, inputs: Mapping[str, Any]) -> bool: ...
    @staticmethod
    def _build_execution_context(run: ExecutionRun, compiled: CompiledStep) -> ExecutionContext: ...
    @staticmethod
    def _build_capability_context(execution_context: ExecutionContext, compiled: CompiledStep, provider_config: Any) -> CapabilityContext: ...
    def _build_runner_context(self, execution_context: ExecutionContext, capability_context: CapabilityContext, step_id: str, middleware_context: MiddlewareContext | None = None) -> RunnerContext: ...
    def _build_invocation(self, run: ExecutionRun, compiled: CompiledStep, request: BaseModel, provider: Any, execution_context: ExecutionContext, capability_context: CapabilityContext, provider_config: Any) -> MiddlewareInvocation: ...
    def _record_run_start(self, run: ExecutionRun, plan: ExecutionPlan) -> None: ...
    async def _record_run_finish(self, run: ExecutionRun, result: ExecutionResult) -> None: ...
    def _record_step_success(self, run: ExecutionRun, compiled: CompiledStep, step: Any, envelope: ResourceEnvelope, provider_config: Any) -> None: ...
    def _record_step_success_metadata(self, run: ExecutionRun, step: Any, envelope: ResourceEnvelope) -> None: ...
    def _record_step_lineage(self, run: ExecutionRun, step: Any, resource_id: UUID, parents: list[str]) -> None: ...
    def _record_step_provenance(self, run: ExecutionRun, step: Any, resource_id: UUID, producer: ProducerRef) -> None: ...
    def _record_metadata(self, record: MetadataRecord) -> None: ...
    async def _handle_step_failure(self, run: ExecutionRun, compiled: CompiledStep, step: Any, exc: Exception) -> None: ...
    @staticmethod
    def _skip_dependents(run: ExecutionRun, failed_step_id: str) -> None: ...
    async def _invoke_compensation(self, run: ExecutionRun, compiled: CompiledStep, error: Exception) -> None: ...
    async def _record_dead_letter(self, run: ExecutionRun, result: ExecutionResult) -> None: ...
    async def resume_from_checkpoint(self, plan: ExecutionPlan, *, run_id: UUID, step_id: str | None = None, inputs: Mapping[str, Any] | None = None, runner: Runner | None = None) -> ExecutionResult: ...
    async def replay_dead_letter(self, plan: ExecutionPlan, *, run_id: UUID, inputs: Mapping[str, Any] | None = None, runner: Runner | None = None) -> ExecutionResult: ...
    def _restore_from_checkpoint(self, run: ExecutionRun, resume_from: tuple[UUID, str]) -> None: ...
    def _save_checkpoint(self, run: ExecutionRun, compiled: CompiledStep, step: Any) -> None: ...
