# ruff: noqa: RUF012
# Generated by Django 6.1 on 2026-08-08 10:31

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []  # type: ignore[var-annotated]

    operations = [
        migrations.CreateModel(
            name="Pipeline",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("slug", models.SlugField(max_length=120)),
                ("name", models.CharField(max_length=200)),
                (
                    "origin",
                    models.CharField(
                        choices=[("code", "Code"), ("managed", "Managed")],
                        default="managed",
                        max_length=20,
                    ),
                ),
                ("is_read_only", models.BooleanField(default=False)),
                ("source_ref", models.CharField(blank=True, max_length=500)),
                ("source_hash", models.CharField(blank=True, max_length=128)),
                ("definition_ref", models.CharField(blank=True, max_length=500)),
                ("current_version_number", models.PositiveIntegerField(default=1)),
                ("current_version_hash", models.CharField(blank=True, max_length=128)),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "ordering": ["project__slug", "slug"],
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("slug", models.SlugField(max_length=120, unique=True)),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "ordering": ["slug"],
            },
        ),
        migrations.CreateModel(
            name="Worker",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "worker_id",
                    models.CharField(max_length=120, primary_key=True, serialize=False),
                ),
                ("backend", models.CharField(blank=True, max_length=120)),
                ("execution_class", models.CharField(default="default", max_length=40)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("online", "Online"),
                            ("offline", "Offline"),
                            ("degraded", "Degraded"),
                        ],
                        default="offline",
                        max_length=20,
                    ),
                ),
                ("heartbeat_at", models.DateTimeField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "ordering": ["worker_id"],
            },
        ),
        migrations.CreateModel(
            name="Checkpoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("run_id", models.UUIDField(db_index=True)),
                ("step_id", models.CharField(max_length=200)),
                ("payload", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "ordering": ["-created_at", "run_id", "step_id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("run_id", "step_id"),
                        name="uniq_mirror_control_checkpoint",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ExecutionRun",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "run_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("pipeline_name", models.CharField(blank=True, max_length=200)),
                (
                    "pipeline_version",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("running", "Running"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="queued",
                        max_length=20,
                    ),
                ),
                ("execution_class", models.CharField(default="default", max_length=40)),
                ("worker_id", models.CharField(blank=True, max_length=120)),
                ("queue_name", models.CharField(blank=True, max_length=120)),
                ("input_payload", models.JSONField(blank=True, default=dict)),
                ("result_payload", models.JSONField(blank=True, default=dict)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "pipeline",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="runs",
                        to="mirror_control_django.pipeline",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "run_id"],
            },
        ),
        migrations.CreateModel(
            name="DeadLetter",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "run_id",
                    models.UUIDField(editable=False, primary_key=True, serialize=False),
                ),
                ("pipeline_name", models.CharField(max_length=200)),
                ("step_id", models.CharField(blank=True, max_length=200)),
                ("reason", models.TextField()),
                ("original_inputs", models.JSONField(blank=True, default=dict)),
                ("policy_state", models.JSONField(blank=True, default=dict)),
                ("provenance", models.JSONField(blank=True, default=dict)),
                ("retry_count", models.PositiveIntegerField(default=0)),
                ("terminal_status", models.CharField(max_length=40)),
                ("worker_id", models.CharField(blank=True, max_length=120)),
                ("lease_id", models.CharField(blank=True, max_length=120)),
                (
                    "pipeline",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dead_letters",
                        to="mirror_control_django.pipeline",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "run_id"],
            },
        ),
        migrations.AddField(
            model_name="pipeline",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pipelines",
                to="mirror_control_django.project",
            ),
        ),
        migrations.CreateModel(
            name="CrawledURL",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("url", models.URLField(max_length=2048)),
                ("run_id", models.UUIDField(blank=True, db_index=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("discovered", "Discovered"),
                            ("fetched", "Fetched"),
                            ("failed", "Failed"),
                        ],
                        default="discovered",
                        max_length=20,
                    ),
                ),
                ("discovered_at", models.DateTimeField(auto_now_add=True)),
                ("fetched_at", models.DateTimeField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "pipeline",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="crawled_urls",
                        to="mirror_control_django.pipeline",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="crawled_urls",
                        to="mirror_control_django.project",
                    ),
                ),
            ],
            options={
                "ordering": ["-discovered_at", "url"],
            },
        ),
        migrations.CreateModel(
            name="Schedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200)),
                ("cron", models.CharField(max_length=200)),
                ("timezone_name", models.CharField(default="UTC", max_length=64)),
                ("enabled", models.BooleanField(default=True)),
                ("next_run_at", models.DateTimeField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "pipeline",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedules",
                        to="mirror_control_django.pipeline",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ExecutionStep",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("step_id", models.CharField(max_length=200)),
                ("capability", models.CharField(max_length=200)),
                ("provider", models.CharField(blank=True, max_length=200)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("running", "Running"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                            ("skipped", "Skipped"),
                        ],
                        default="queued",
                        max_length=20,
                    ),
                ),
                ("input_payload", models.JSONField(blank=True, default=dict)),
                ("output_payload", models.JSONField(blank=True, default=dict)),
                ("error_text", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="steps",
                        to="mirror_control_django.executionrun",
                    ),
                ),
            ],
            options={
                "ordering": ["run__created_at", "run_id", "step_id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("run", "step_id"),
                        name="uniq_mirror_control_execution_step",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ArchiveRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("run_id", models.UUIDField(blank=True, db_index=True, null=True)),
                ("resource_key", models.CharField(max_length=500)),
                ("storage_ref", models.CharField(max_length=500)),
                ("mime_type", models.CharField(blank=True, max_length=120)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "pipeline",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="archives",
                        to="mirror_control_django.pipeline",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "resource_key"],
                "indexes": [models.Index(fields=["resource_key"], name="mirror_cont_resourc_df8942_idx")],
            },
        ),
        migrations.CreateModel(
            name="PipelineVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.PositiveIntegerField()),
                ("definition_ref", models.CharField(max_length=500)),
                ("definition_hash", models.CharField(max_length=128)),
                ("definition_format", models.CharField(default="json", max_length=20)),
                ("notes", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "pipeline",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="mirror_control_django.pipeline",
                    ),
                ),
            ],
            options={
                "ordering": ["pipeline__project__slug", "pipeline__slug", "version"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("pipeline", "version"),
                        name="uniq_mirror_control_pipeline_version",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="pipeline",
            constraint=models.UniqueConstraint(fields=("project", "slug"), name="uniq_mirror_control_pipeline_slug"),
        ),
        migrations.AddIndex(
            model_name="crawledurl",
            index=models.Index(fields=["url"], name="mirror_cont_url_5c91ed_idx"),
        ),
        migrations.AddConstraint(
            model_name="schedule",
            constraint=models.UniqueConstraint(fields=("pipeline", "name"), name="uniq_mirror_control_schedule"),
        ),
    ]
